# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omnishell < Formula
  desc "Modular, declarative terminal configuration for macOS and Linux"
  homepage "https://github.com/JtheGunner/omnishell"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.5.0/omnishell_darwin_amd64.tar.gz"
      sha256 "a603344043319854013f3b7ef7b8dbc653f1e3b24675a732f9fabf8fadcff996"

      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.5.0/omnishell_darwin_arm64.tar.gz"
      sha256 "51d33ec2cd9993a027fa3f858ba322cd09e972b065f10e30be09955e20345be5"

      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.5.0/omnishell_linux_amd64.tar.gz"
      sha256 "e3ffaf966f6114d4cb3c49cab2545715cee6e74b44beed1b0e6dbe18d7fb105c"
      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.5.0/omnishell_linux_arm64.tar.gz"
      sha256 "61c9033a992ee07e9627304f43f54d981a7186cf8e05afec9146188b12f2abd7"
      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/omnishell version"
  end
end
