# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omnishell < Formula
  desc "Modular, declarative terminal configuration for macOS and Linux"
  homepage "https://github.com/JtheGunner/omnishell"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.3.2/omnishell_darwin_amd64.tar.gz"
      sha256 "bd5b142fbec5606fca6fed6e34ac034d90665b2f55b335939b0d129f0f765a75"

      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.3.2/omnishell_darwin_arm64.tar.gz"
      sha256 "5b90dd8bd36455d133e133264a86d9fb22f9eaed7cb333ed7e7cd4a018753cf8"

      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.3.2/omnishell_linux_amd64.tar.gz"
      sha256 "c395194540823f9f53d896ed33988b7fcad3a7fb04e4cce11b0b5c1ee4ed425e"
      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JtheGunner/omnishell/releases/download/v0.3.2/omnishell_linux_arm64.tar.gz"
      sha256 "a8b9d4c21155145daeaf84919292e4a7014e184b7b642a0a6595892202c73233"
      define_method(:install) do
        bin.install "omnishell"
        bash_completion.install "completions/omnishell.bash" => "omnishell"
        zsh_completion.install "completions/_omnishell"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/omnishell version"
  end
end
